<TaskSphere>:
    Button:
        pos: root.center_x - (self.width/2), root.center_y
        background_color: 1,1,1,.3
        canvas:
            Color:
                rgba: 227,236,221,1
            Ellipse:
                pos: root.center_x - (self.width/2), root.center_y
    Label:
        text: 'Test Label'
        bold: True
        color: 0,1,0,1
        font_size: 20
        pos: root.center_x - (self.width/2), root.center_y

