<TaskSphere>:
    FloatLayout:
        canvas:
            Color:
                rgba: 227,236,221,1
            Ellipse:
                pos: root.center_x - 50, root.center_y
        Button:
            pos: root.center_x - (self.width/2), root.center_y
            background_color: 1,1,1,.3
        Label:
            text: app.name
            bold: True
            color: 0,1,0,1
            font_size: 20
            pos: root.center_x - (self.width/2), root.center_y
